---
# This workflow integrates ShiftLeft NG SAST with GitHub
# Visit https://docs.shiftleft.io for help
name: ShiftLeft

on:
  pull_request:
  workflow_dispatch:
  
jobs:
  NextGen-Static-Analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download ShiftLeft CLI
      run: |
        curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: NextGen Static Analysis
      run: ${GITHUB_WORKSPACE}/sl analyze --wait --app le-aws-cloudwatch --tag branch=${{ github.head_ref || steps.extract_branch.outputs.branch }} --python $(pwd)
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
    - name: Upload report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: reports
        
   
  ## Uncomment the following section to enable build rule checking and enforcing.
  #Build-Rules: 
    #runs-on: ubuntu-latest
    #needs: NextGen-Static-Analysis
    #steps:
    #- uses: actions/checkout@v2
    #- name: Download ShiftLeft CLI
    #  run: |
    #    curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl
    #- name: Validate Build Rules
    #  run: sleep 10s && ${GITHUB_WORKSPACE}/sl check-analysis --app le-aws-cloudwatch --source 'tag.branch=${{ github.event.pull_request.base.ref }}' --target "tag.branch=${{ github.head_ref || steps.extract_branch.outputs.branch }}"
    #  env:
        #SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
        
