name: ShiftLeft Scan

on:
  push:
    branches:
      - master
      - feature/*
  #schedule:
  #  - cron: "0 */4 * * *"
  pull_request: # include to analyze when you create a pull request
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Perform ShiftLeft Scan
      uses: ShiftLeftSecurity/scan-action@master
      with:
        output: reports
      env:
        WORKSPACE: ""
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SCAN_AUTO_BUILD: true
    - name: Upload scan reports
      uses: actions/upload-artifact@v1.0.0
      with:
        name: shiftleft-scan-reports
        path: reports
    - name: Upload report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: reports